name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: demur_nodia.tex
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: demur_nodia.pdf
          path: demur_nodia.pdf
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update compiled files
